- name: install gpg
  become: yes
  apt:
    name: gnupg,software-properties-common
    state: present

- name: add gpg hey
  become: yes
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    validate_certs: no

- name: add repository
  become: yes
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"             
    state: present
    validate_certs: no

- name: install grafana
  become: yes
  apt:
    name: grafana
    state: latest
    
- name: Grafana configuration file copy
  become: yes
  template:
    src: "grafana.ini.j2"
    dest: /etc/grafana/grafana.ini

- name: Copy grafana datasource_dashboard
  become: yes
  copy:
    src: "{{ item }}/"
    dest: "/etc/grafana/provisioning/{{ item }}"
    directory_mode: 0750
#    owner: "{{userId}}"
    group: "grafana"
#    remote_src: yes
    mode: 0744
  with_items:
    - datasources
    - dashboards

- name: start service grafana-server
  become: yes
  systemd:
    name: grafana-server
    state: started
    enabled: yes
    
- name: Check service up
  uri:
    url: http://localhost:3000
    method: GET
    status_code: 200
  register: _result
  until: _result.status == 200
  retries: 60
  delay: 1

- name: change admin password for grafana gui
  become: yes
  shell : "grafana-cli admin reset-admin-password {{ admin_pass }}"