- name: Restart the Prometheus service
  become: true
  service:
    name: prometheus
    state: restarted
  listen: event_restart_prometheus

- name: Reload systemd
  become: true
  command: systemctl daemon-reload
  listen: systemd_reload