---
- name: Install NGINX and deps
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx-full
    - php-fpm 
    - php-mysql
    - git
       
- name: Create NGINX Conf File
  become: yes
  template:
    src: templates/wordpress.conf.j2
    dest: /etc/nginx/sites-available/wordpress.conf
    
- name: Activate site configuration
  become: yes
  file:
    src: '/etc/nginx/sites-available/wordpress.conf'
    dest: '/etc/nginx/sites-enabled/wordpress.conf'
    state: 'link'
  
- name: Create directory for WordPress
  become: yes
  file:
    path: "{{ wp_dir }}"
    state: "directory"
    owner: "www-data"
    group: "www-data"  
    
- name: download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: "/tmp/latest.tar.gz"
    
- name: unpack WordPress installation
  become: yes
  shell: "tar -xvf /tmp/latest.tar.gz --strip-components=1 -C {{ wp_dir }}"
    
#- name: Download and unpack latest WordPress
#  become: yes
#  unarchive:
#    src: https://wordpress.org/latest.tar.gz
#    dest: "{{ wp_dir }}"
#    remote_src: yes
#    creates: "{{ wp_dir }}"
#    unsafe_writes: yes
#    keep_newer: yes
- name: Set up wp-config
  become: yes
  template:
    src: "templates/wp-config.php.j2"
    dest: "{{ wp_dir }}/wp-config.php"
    
- name: Set up HyperDB config
  become: yes
  template:
    src: "templates/db-config.php.j2"
    dest: "{{ wp_dir }}/db-config.php"
    
- name: Activate HyperDB plugin
  become: yes
  template:
    src: "templates/db.php.j2"
    dest: "{{ wp_dir }}/wp-content/db.php"
    
- name: Set www-data ownership
  become: yes
  file:
    path: "{{ wp_dir }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data

- name: Set permissions for directories
  become: yes
  shell: "/usr/bin/find {{ wp_dir }} -type d -exec chmod 750 {} \\;"

- name: Set permissions for files
  become: yes
  shell: "/usr/bin/find {{ wp_dir }} -type f -exec chmod 640 {} \\;"

- name: Disable NGINX Default Virtual Host
  become: yes
  command:
    cmd: unlink /etc/nginx/sites-enabled/default

- name: Restart nginx
  become: yes
  service:
    name: nginx
    state: restarted
    enabled: yes

